<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\TesteRepresentacional;

class TesteRepresentacionalEventosSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'uuid' => 'a04efcf4-abc6-4e42-a446-1b813d80467b',
                'name' => 'Priscila Cândida Lima Sobral',
                'email' => 'priscilacandidalimasobral@gmail.com',
                'phone' => '(34) 99235-4108',
                'answers' => json_encode([
                    "Q1_V" => "4",
                    "Q1_A" => "2",
                    "Q1_C" => "1",
                    "Q1_D" => "3",
                    "Q2_A" => "4",
                    "Q2_V" => "2",
                    "Q2_D" => "1",
                    "Q2_C" => "3",
                    "Q3_V" => "1",
                    "Q3_C" => "4",
                    "Q3_D" => "2",
                    "Q3_A" => "3",
                    "Q4_A" => "3",
                    "Q4_D" => "4",
                    "Q4_C" => "1",
                    "Q4_V" => "2",
                    "Q5_A" => "3",
                    "Q5_D" => "4",
                    "Q5_C" => "2",
                    "Q5_V" => "1"
                ]),
                'scores' => json_encode(["A" => 15, "D" => 14, "C" => 11, "V" => 10]),
                'percentual' => json_encode(["V" => 20, "A" => 30, "C" => 22, "D" => 28]),
                'primary' => 'A',
                'secondary' => 'D',
            ],
            [
                'uuid' => 'a04efd63-7163-4424-8cfd-f27869300473',
                'name' => 'RICARDO FERNANDES SILVA',
                'email' => 'rdo_fernandes@hotmail.com',
                'phone' => '(34) 98820-1007',
                'answers' => json_encode([
                    "Q1_V" => "3",
                    "Q1_A" => "4",
                    "Q1_C" => "1",
                    "Q1_D" => "2",
                    "Q2_A" => "2",
                    "Q2_V" => "1",
                    "Q2_D" => "3",
                    "Q2_C" => "4",
                    "Q3_V" => "1",
                    "Q3_C" => "2",
                    "Q3_D" => "3",
                    "Q3_A" => "4",
                    "Q4_A" => "4",
                    "Q4_D" => "3",
                    "Q4_C" => "2",
                    "Q4_V" => "1",
                    "Q5_A" => "3",
                    "Q5_D" => "4",
                    "Q5_C" => "2",
                    "Q5_V" => "1"
                ]),
                'scores' => json_encode(["A" => 17, "D" => 15, "C" => 11, "V" => 7]),
                'percentual' => json_encode(["V" => 14, "A" => 34, "C" => 22, "D" => 30]),
                'primary' => 'A',
                'secondary' => 'D',
            ],
            [
                'uuid' => 'a04efd76-4e28-4bca-9474-050afe82e2cb',
                'name' => 'Marcos Vinicius Moura Oliveira',
                'email' => 'marcosmoura.1@hotmail.com',
                'phone' => '(34) 98432-9888',
                'answers' => json_encode([
                    "Q1_V" => "1",
                    "Q1_A" => "2",
                    "Q1_C" => "3",
                    "Q1_D" => "4",
                    "Q2_A" => "1",
                    "Q2_V" => "3",
                    "Q2_D" => "4",
                    "Q2_C" => "2",
                    "Q3_V" => "1",
                    "Q3_C" => "2",
                    "Q3_D" => "3",
                    "Q3_A" => "4",
                    "Q4_A" => "1",
                    "Q4_D" => "4",
                    "Q4_C" => "2",
                    "Q4_V" => "3",
                    "Q5_A" => "1",
                    "Q5_D" => "4",
                    "Q5_C" => "3",
                    "Q5_V" => "2"
                ]),
                'scores' => json_encode(["D" => 19, "C" => 12, "V" => 10, "A" => 9]),
                'percentual' => json_encode(["V" => 20, "A" => 18, "C" => 24, "D" => 38]),
                'primary' => 'D',
                'secondary' => 'C',
            ],
            [
                'uuid' => 'a04efd79-60b0-4988-a4d1-1535ce5eeda0',
                'name' => 'Laura dos Santos Silva Monteiro',
                'email' => 'laurasantossmonteiro@gmail.com',
                'phone' => '(34) 99102-7429',
                'answers' => json_encode([
                    "Q1_V" => "4",
                    "Q1_A" => "3",
                    "Q1_C" => "2",
                    "Q1_D" => "1",
                    "Q2_A" => "1",
                    "Q2_V" => "2",
                    "Q2_D" => "4",
                    "Q2_C" => "3",
                    "Q3_V" => "1",
                    "Q3_C" => "2",
                    "Q3_D" => "4",
                    "Q3_A" => "3",
                    "Q4_A" => "1",
                    "Q4_D" => "3",
                    "Q4_C" => "2",
                    "Q4_V" => "4",
                    "Q5_A" => "3",
                    "Q5_D" => "2",
                    "Q5_C" => "1",
                    "Q5_V" => "4"
                ]),
                'scores' => json_encode(["V" => 15, "D" => 14, "A" => 11, "C" => 10]),
                'percentual' => json_encode(["V" => 30, "A" => 22, "C" => 20, "D" => 28]),
                'primary' => 'V',
                'secondary' => 'D',
            ],
            [
                'uuid' => 'a04f0008-8b7d-4d33-ab82-0bc3e0f97958',
                'name' => 'Karina Correa Machado',
                'email' => 'karinacmachado16@gmail.com',
                'phone' => '(34) 99827-8856',
                'answers' => json_encode([
                    "Q1_V" => "2",
                    "Q1_A" => "1",
                    "Q1_C" => "4",
                    "Q1_D" => "3",
                    "Q2_A" => "3",
                    "Q2_V" => "1",
                    "Q2_D" => "4",
                    "Q2_C" => "2",
                    "Q3_V" => "2",
                    "Q3_C" => "4",
                    "Q3_D" => "1",
                    "Q3_A" => "3",
                    "Q4_A" => "4",
                    "Q4_D" => "2",
                    "Q4_C" => "1",
                    "Q4_V" => "3",
                    "Q5_A" => "3",
                    "Q5_D" => "2",
                    "Q5_C" => "1",
                    "Q5_V" => "4"
                ]),
                'scores' => json_encode(["A" => 14, "C" => 12, "D" => 12, "V" => 10]),
                'percentual' => json_encode(["V" => 20, "A" => 28, "C" => 24, "D" => 24]),
                'primary' => 'A',
                'secondary' => 'C',
            ],
            [
                'uuid' => 'a04f0059-40e5-4c93-8a36-73ea87f001bf',
                'name' => 'Amanda Cristina Silva',
                'email' => 'amandacristinasilva740@gmail.com',
                'phone' => '(34) 99190-6920',
                'answers' => json_encode([
                    "Q1_V" => "1",
                    "Q1_A" => "2",
                    "Q1_C" => "4",
                    "Q1_D" => "3",
                    "Q2_A" => "1",
                    "Q2_V" => "4",
                    "Q2_D" => "3",
                    "Q2_C" => "2",
                    "Q3_V" => "2",
                    "Q3_C" => "1",
                    "Q3_D" => "4",
                    "Q3_A" => "3",
                    "Q4_A" => "2",
                    "Q4_D" => "4",
                    "Q4_C" => "3",
                    "Q4_V" => "1",
                    "Q5_A" => "3",
                    "Q5_D" => "2",
                    "Q5_C" => "4",
                    "Q5_V" => "1"
                ]),
                'scores' => json_encode(["A" => 12, "D" => 14, "C" => 12, "V" => 8]),
                'percentual' => json_encode(["V" => 16, "A" => 24, "C" => 24, "D" => 28]),
                'primary' => 'D',
                'secondary' => 'A',
            ],
            [
                'uuid' => 'a04f007a-0ae7-49c1-8e2f-be5937995bc7',
                'name' => 'Debora Cristina Rodrigues',
                'email' => 'rodriguesdebora044@gmail.com',
                'phone' => '(34) 98134-0267',
                'answers' => json_encode([
                    "Q1_V" => "4",
                    "Q1_A" => "3",
                    "Q1_C" => "1",
                    "Q1_D" => "2",
                    "Q2_A" => "2",
                    "Q2_V" => "4",
                    "Q2_D" => "1",
                    "Q2_C" => "3",
                    "Q3_V" => "2",
                    "Q3_C" => "4",
                    "Q3_D" => "3",
                    "Q3_A" => "1",
                    "Q4_A" => "3",
                    "Q4_D" => "4",
                    "Q4_C" => "1",
                    "Q4_V" => "2",
                    "Q5_A" => "4",
                    "Q5_D" => "3",
                    "Q5_C" => "2",
                    "Q5_V" => "1"
                ]),
                'scores' => json_encode(["A" => 16, "D" => 14, "C" => 8, "V" => 12]),
                'percentual' => json_encode(["V" => 24, "A" => 32, "C" => 16, "D" => 28]),
                'primary' => 'A',
                'secondary' => 'D',
            ],
            [
                'uuid' => 'a04f00ae-3804-41fe-ab3d-afbc2087ca94',
                'name' => 'Rafaela Carvalho',
                'email' => 'rafaelacarvalho148@gmail.com',
                'phone' => '(34) 99916-1778',
                'answers' => json_encode([
                    "Q1_V" => "4",
                    "Q1_A" => "3",
                    "Q1_C" => "2",
                    "Q1_D" => "1",
                    "Q2_A" => "3",
                    "Q2_V" => "4",
                    "Q2_D" => "2",
                    "Q2_C" => "1",
                    "Q3_V" => "4",
                    "Q3_C" => "3",
                    "Q3_D" => "2",
                    "Q3_A" => "1",
                    "Q4_A" => "2",
                    "Q4_D" => "4",
                    "Q4_C" => "1",
                    "Q4_V" => "3",
                    "Q5_A" => "3",
                    "Q5_D" => "4",
                    "Q5_C" => "2",
                    "Q5_V" => "1"
                ]),
                'scores' => json_encode(["V" => 16, "D" => 15, "A" => 12, "C" => 7]),
                'percentual' => json_encode(["V" => 32, "A" => 24, "C" => 14, "D" => 30]),
                'primary' => 'V',
                'secondary' => 'D',
            ],
            [
                'uuid' => 'a04f012b-b93a-4b48-931f-5f2f9c8eb5c2',
                'name' => 'Maria Fernanda Goncalves',
                'email' => 'mafe.goncalves@hotmail.com',
                'phone' => '(34) 99903-8631',
                'answers' => json_encode([
                    "Q1_V" => "2",
                    "Q1_A" => "3",
                    "Q1_C" => "4",
                    "Q1_D" => "1",
                    "Q2_A" => "3",
                    "Q2_V" => "2",
                    "Q2_D" => "4",
                    "Q2_C" => "1",
                    "Q3_V" => "4",
                    "Q3_C" => "3",
                    "Q3_D" => "2",
                    "Q3_A" => "1",
                    "Q4_A" => "2",
                    "Q4_D" => "4",
                    "Q4_C" => "3",
                    "Q4_V" => "1",
                    "Q5_A" => "4",
                    "Q5_D" => "3",
                    "Q5_C" => "2",
                    "Q5_V" => "1"
                ]),
                'scores' => json_encode(["A" => 14, "D" => 14, "C" => 12, "V" => 10]),
                'percentual' => json_encode(["V" => 20, "A" => 28, "C" => 24, "D" => 28]),
                'primary' => 'A',
                'secondary' => 'D',
            ],
            [
                'uuid' => 'a04f015d-b0f8-4dae-90c1-89b3cd384a93',
                'name' => 'Nayara Cristina da Silva',
                'email' => 'nayaracristina.silva89@gmail.com',
                'phone' => '(34) 99980-8789',
                'answers' => json_encode([
                    "Q1_V" => "3",
                    "Q1_A" => "2",
                    "Q1_C" => "4",
                    "Q1_D" => "1",
                    "Q2_A" => "1",
                    "Q2_V" => "3",
                    "Q2_D" => "4",
                    "Q2_C" => "2",
                    "Q3_V" => "2",
                    "Q3_C" => "1",
                    "Q3_D" => "3",
                    "Q3_A" => "4",
                    "Q4_A" => "3",
                    "Q4_D" => "4",
                    "Q4_C" => "1",
                    "Q4_V" => "2",
                    "Q5_A" => "4",
                    "Q5_D" => "1",
                    "Q5_C" => "2",
                    "Q5_V" => "3"
                ]),
                'scores' => json_encode(["A" => 13, "D" => 13, "C" => 10, "V" => 12]),
                'percentual' => json_encode(["V" => 24, "A" => 26, "C" => 20, "D" => 26]),
                'primary' => 'A',
                'secondary' => 'D',
            ],
            [
                'uuid' => 'a04f01e7-b7bb-4250-a13d-b13b105f1ba4',
                'name' => 'Larissa Alves de Souza',
                'email' => 'larissaalvess400@gmail.com',
                'phone' => '(34) 99628-2966',
                'answers' => json_encode([
                    "Q1_V" => "2",
                    "Q1_A" => "1",
                    "Q1_C" => "4",
                    "Q1_D" => "3",
                    "Q2_A" => "2",
                    "Q2_V" => "3",
                    "Q2_D" => "4",
                    "Q2_C" => "1",
                    "Q3_V" => "3",
                    "Q3_C" => "4",
                    "Q3_D" => "2",
                    "Q3_A" => "1",
                    "Q4_A" => "2",
                    "Q4_D" => "3",
                    "Q4_C" => "4",
                    "Q4_V" => "1",
                    "Q5_A" => "3",
                    "Q5_D" => "2",
                    "Q5_C" => "4",
                    "Q5_V" => "1"
                ]),
                'scores' => json_encode(["A" => 10, "D" => 14, "C" => 16, "V" => 10]),
                'percentual' => json_encode(["V" => 20, "A" => 20, "C" => 32, "D" => 28]),
                'primary' => 'C',
                'secondary' => 'D',
            ],
            [
                'uuid' => 'a04f0267-6f04-4aef-8363-4d0b7d2d7f36',
                'name' => 'Ana Júlia Ribeiro',
                'email' => 'anajuliaribeiro@gmail.com',
                'phone' => '(34) 99692-7717',
                'answers' => json_encode([
                    "Q1_V" => "3",
                    "Q1_A" => "1",
                    "Q1_C" => "4",
                    "Q1_D" => "2",
                    "Q2_A" => "4",
                    "Q2_V" => "3",
                    "Q2_D" => "1",
                    "Q2_C" => "2",
                    "Q3_V" => "3",
                    "Q3_C" => "2",
                    "Q3_D" => "1",
                    "Q3_A" => "4",
                    "Q4_A" => "4",
                    "Q4_D" => "3",
                    "Q4_C" => "1",
                    "Q4_V" => "2",
                    "Q5_A" => "3",
                    "Q5_D" => "2",
                    "Q5_C" => "1",
                    "Q5_V" => "4"
                ]),
                'scores' => json_encode(["A" => 15, "D" => 12, "C" => 9, "V" => 14]),
                'percentual' => json_encode(["V" => 28, "A" => 30, "C" => 18, "D" => 24]),
                'primary' => 'A',
                'secondary' => 'V',
            ],
            [
                'uuid' => 'a04f02df-7e17-4df0-aa44-706a2e547c2c',
                'name' => 'Carolina Silva Andrade',
                'email' => 'carolandrade@gmail.com',
                'phone' => '(34) 98876-9987',
                'answers' => json_encode([
                    "Q1_V" => "1",
                    "Q1_A" => "4",
                    "Q1_C" => "2",
                    "Q1_D" => "3",
                    "Q2_A" => "3",
                    "Q2_V" => "4",
                    "Q2_D" => "1",
                    "Q2_C" => "2",
                    "Q3_V" => "2",
                    "Q3_C" => "3",
                    "Q3_D" => "4",
                    "Q3_A" => "1",
                    "Q4_A" => "4",
                    "Q4_D" => "1",
                    "Q4_C" => "2",
                    "Q4_V" => "3",
                    "Q5_A" => "4",
                    "Q5_D" => "3",
                    "Q5_C" => "1",
                    "Q5_V" => "2"
                ]),
                'scores' => json_encode(["A" => 16, "D" => 12, "C" => 8, "V" => 12]),
                'percentual' => json_encode(["V" => 24, "A" => 32, "C" => 16, "D" => 24]),
                'primary' => 'A',
                'secondary' => 'V',
            ],

        ];

        foreach ($data as $item) {
            TesteRepresentacional::create($item);
        }
    }
}
